var $hx_exports="undefined"!=typeof exports?exports:"undefined"!=typeof window?window:"undefined"!=typeof self?self:this;
(function(Qb){$hx_exports.delaunator=$hx_exports.delaunator||{};var q=$hx_exports.delaunator.Delaunator=function(a){var b=a.length>>1;this.coords=a;a=Math.max(2*b-5,0)|0;this.triangles=new Uint32Array(3*a);this.halfedges=new Int32Array(3*a);this.hashSize=Math.ceil(Math.sqrt(b));this.hullPrev=new Uint32Array(b);this.hullNext=new Uint32Array(b);this.hullTri=new Uint32Array(b);this.hullHash=(new Int32Array(this.hashSize)).fill(-1);this.ids=new Uint32Array(b);this.dists=new Float64Array(b);this.trianglesLen=
0;this.center=new ba(0,0);this.update()};q.from=function(a){for(var b=new Float32Array(2*a.length),c=0,d=a.length;c<d;){var e=c++,g=a[e];b[2*e]=g[0];b[2*e+1]=g[1]}return new q(b)};q.fromPoints=function(a){for(var b=new Float32Array(2*a.length),c=0,d=a.length;c<d;){var e=c++,g=a[e];b[2*e]=g.x;b[2*e+1]=g.y}return new q(b)};q.prototype={update:function(){for(var a=this.coords.length>>1,b=Infinity,c=Infinity,d=-Infinity,e=-Infinity,g=0;g<a;){var f=g++,h=this.coords[2*f],v=this.coords[2*f+1];h<b&&(b=h);
v<c&&(c=v);h>d&&(d=h);v>e&&(e=v);this.ids[f]=f}for(var z=.5*(b+d),y=.5*(c+e),w=Infinity,l=0,m=0,n=0,L=0;L<a;){var ca=L++,Pa=z-this.coords[2*ca],Qa=y-this.coords[2*ca+1],Ra=Pa*Pa+Qa*Qa;Ra<w&&(l=ca,w=Ra)}var C=this.coords[2*l],D=this.coords[2*l+1];w=Infinity;for(var Sa=0;Sa<a;){var O=Sa++;if(O!=l){var Ta=C-this.coords[2*O],Ua=D-this.coords[2*O+1],da=Ta*Ta+Ua*Ua;da<w&&0<da&&(m=O,w=da)}}for(var A=this.coords[2*m],B=this.coords[2*m+1],ea=Infinity,Va=0;Va<a;){var M=Va++;if(M!=l&&M!=m){var Wa=this.circumradius(C,
D,A,B,this.coords[2*M],this.coords[2*M+1]);Wa<ea&&(n=M,ea=Wa)}}var E=this.coords[2*n],F=this.coords[2*n+1];if(Infinity!=ea){var fa=(D-F)*(A-E),ha=(C-E)*(B-F),Xa=Math.abs(fa-ha)>=3.3306690738754716E-16*Math.abs(fa+ha)?fa-ha:0;if(0!=Xa)var ia=Xa;else{var ja=(B-D)*(E-C),ka=(A-C)*(F-D);ia=Math.abs(ja-ka)>=3.3306690738754716E-16*Math.abs(ja+ka)?ja-ka:0}if(0!=ia)var Ya=ia;else{var la=(F-B)*(C-A),ma=(E-A)*(D-B);Ya=Math.abs(la-ma)>=3.3306690738754716E-16*Math.abs(la+ma)?la-ma:0}if(0>Ya){var ba=m,Jb=A,Kb=
B;m=n;A=E;B=F;n=ba;E=Jb;F=Kb}this.circumcenter(this.center,C,D,A,B,E,F);for(var Za=0;Za<a;){var na=Za++,$a=this.coords[2*na]-this.center.x,ab=this.coords[2*na+1]-this.center.y;this.dists[na]=$a*$a+ab*ab}this.quicksort(0,a-1);this.hullStart=l;var N=3;this.hullPrev[n]=m;this.hullNext[l]=m;this.hullPrev[l]=n;this.hullNext[m]=n;this.hullPrev[m]=l;this.hullNext[n]=l;this.hullTri[l]=0;this.hullTri[m]=1;this.hullTri[n]=2;this.hullHash.fill(-1);var bb=C-this.center.x,cb=D-this.center.y,db=bb/(Math.abs(bb)+
Math.abs(cb));this.hullHash[Math.floor((0<cb?3-db:1+db)/4*this.hashSize)%this.hashSize]=l;var eb=A-this.center.x,fb=B-this.center.y,gb=eb/(Math.abs(eb)+Math.abs(fb));this.hullHash[Math.floor((0<fb?3-gb:1+gb)/4*this.hashSize)%this.hashSize]=m;var hb=E-this.center.x,ib=F-this.center.y,jb=hb/(Math.abs(hb)+Math.abs(ib));this.hullHash[Math.floor((0<ib?3-jb:1+jb)/4*this.hashSize)%this.hashSize]=n;var K=this.trianglesLen=0;this.triangles[K]=l;this.triangles[K+1]=m;this.triangles[K+2]=n;this.halfedges[K]=
-1;this.halfedges[K+1]=-1;this.halfedges[K+2]=-1;this.trianglesLen+=3;for(var kb=0,lb=0,mb=0,Lb=this.ids.length;mb<Lb;){var nb=mb++,r=this.ids[nb],t=this.coords[2*r],u=this.coords[2*r+1];if(!(0<nb&&Math.abs(t-kb)<=q.EPSILON&&Math.abs(u-lb)<=q.EPSILON)&&(kb=t,lb=u,r!=l&&r!=m&&r!=n)){for(var G=0,ob=t-this.center.x,pb=u-this.center.y,qb=ob/(Math.abs(ob)+Math.abs(pb)),Mb=Math.floor((0<pb?3-qb:1+qb)/4*this.hashSize)%this.hashSize,rb=0,Nb=this.hashSize;rb<Nb&&(G=this.hullHash[(Mb+rb++)%this.hashSize],-1==
G||G==this.hullNext[G]););for(var k=G=this.hullPrev[G],p=this.hullNext[k];;){var P=this.coords[2*k],Q=this.coords[2*k+1],R=this.coords[2*p],S=this.coords[2*p+1],oa=(u-S)*(P-R),pa=(t-R)*(Q-S),sb=Math.abs(oa-pa)>=3.3306690738754716E-16*Math.abs(oa+pa)?oa-pa:0;if(0!=sb)var qa=sb;else{var ra=(Q-u)*(R-t),sa=(P-t)*(S-u);qa=Math.abs(ra-sa)>=3.3306690738754716E-16*Math.abs(ra+sa)?ra-sa:0}if(0!=qa)var tb=qa;else{var ta=(S-Q)*(t-P),ua=(R-P)*(u-Q);tb=Math.abs(ta-ua)>=3.3306690738754716E-16*Math.abs(ta+ua)?ta-
ua:0}if(0>tb)break;k=p;if(k==G){k=-1;break}p=this.hullNext[k]}if(-1!=k){var Ob=this.hullNext[k],va=this.hullTri[k],H=this.trianglesLen;this.triangles[H]=k;this.triangles[H+1]=r;this.triangles[H+2]=Ob;this.halfedges[H]=-1;this.halfedges[H+1]=-1;var ub=H+2;this.halfedges[ub]=va;-1!=va&&(this.halfedges[va]=ub);this.trianglesLen+=3;this.hullTri[r]=this.legalize(H+2);this.hullTri[k]=H;++N;var x=this.hullNext[k];for(p=this.hullNext[x];;){var T=this.coords[2*x],U=this.coords[2*x+1],V=this.coords[2*p],W=
this.coords[2*p+1],wa=(u-W)*(T-V),xa=(t-V)*(U-W),vb=Math.abs(wa-xa)>=3.3306690738754716E-16*Math.abs(wa+xa)?wa-xa:0;if(0!=vb)var ya=vb;else{var za=(U-u)*(V-t),Aa=(T-t)*(W-u);ya=Math.abs(za-Aa)>=3.3306690738754716E-16*Math.abs(za+Aa)?za-Aa:0}if(0!=ya)var wb=ya;else{var Ba=(W-U)*(t-T),Ca=(V-T)*(u-U);wb=Math.abs(Ba-Ca)>=3.3306690738754716E-16*Math.abs(Ba+Ca)?Ba-Ca:0}if(!(0>wb))break;var Da=this.hullTri[r],Ea=this.hullTri[x],I=this.trianglesLen;this.triangles[I]=x;this.triangles[I+1]=r;this.triangles[I+
2]=p;this.halfedges[I]=Da;-1!=Da&&(this.halfedges[Da]=I);this.halfedges[I+1]=-1;var xb=I+2;this.halfedges[xb]=Ea;-1!=Ea&&(this.halfedges[Ea]=xb);this.trianglesLen+=3;this.hullTri[r]=this.legalize(I+2);this.hullNext[x]=x;--N;x=p;p=this.hullNext[x]}if(k==G)for(p=this.hullPrev[k];;){var X=this.coords[2*p],Y=this.coords[2*p+1],Z=this.coords[2*k],aa=this.coords[2*k+1],Fa=(u-aa)*(X-Z),Ga=(t-Z)*(Y-aa),yb=Math.abs(Fa-Ga)>=3.3306690738754716E-16*Math.abs(Fa+Ga)?Fa-Ga:0;if(0!=yb)var Ha=yb;else{var Ia=(Y-u)*
(Z-t),Ja=(X-t)*(aa-u);Ha=Math.abs(Ia-Ja)>=3.3306690738754716E-16*Math.abs(Ia+Ja)?Ia-Ja:0}if(0!=Ha)var zb=Ha;else{var Ka=(aa-Y)*(t-X),La=(Z-X)*(u-Y);zb=Math.abs(Ka-La)>=3.3306690738754716E-16*Math.abs(Ka+La)?Ka-La:0}if(!(0>zb))break;var Ma=this.hullTri[k],Na=this.hullTri[p],J=this.trianglesLen;this.triangles[J]=p;this.triangles[J+1]=r;this.triangles[J+2]=k;this.halfedges[J]=-1;var Ab=J+1;this.halfedges[Ab]=Ma;-1!=Ma&&(this.halfedges[Ma]=Ab);var Bb=J+2;this.halfedges[Bb]=Na;-1!=Na&&(this.halfedges[Na]=
Bb);this.trianglesLen+=3;this.legalize(J+2);this.hullTri[p]=J;this.hullNext[k]=k;--N;k=p;p=this.hullPrev[k]}this.hullStart=this.hullPrev[r]=k;this.hullPrev[x]=r;this.hullNext[k]=r;this.hullNext[r]=x;var Cb=t-this.center.x,Db=u-this.center.y,Eb=Cb/(Math.abs(Cb)+Math.abs(Db));this.hullHash[Math.floor((0<Db?3-Eb:1+Eb)/4*this.hashSize)%this.hashSize]=r;var Fb=this.coords[2*k]-this.center.x,Gb=this.coords[2*k+1]-this.center.y,Hb=Fb/(Math.abs(Fb)+Math.abs(Gb));this.hullHash[Math.floor((0<Gb?3-Hb:1+Hb)/
4*this.hashSize)%this.hashSize]=k}}}this.hull=new Int32Array(N);for(var Oa=this.hullStart,Ib=0,Pb=N;Ib<Pb;)this.hull[Ib++]=Oa,Oa=this.hullNext[Oa];this.triangles=this.triangles.subarray(0,this.trianglesLen);this.halfedges=this.halfedges.subarray(0,this.trianglesLen)}},legalize:function(a){for(var b=0,c;;){var d=this.halfedges[a],e=a-a%3;c=e+(a+2)%3;if(-1==d){if(0==b)break;a=q.EDGE_STACK[--b]}else{var g=d-d%3,f=g+(d+2)%3,h=this.triangles[c],v=this.triangles[a],z=this.triangles[e+(a+1)%3];e=this.triangles[f];
var y=this.coords[2*e],w=this.coords[2*e+1],l=this.coords[2*h]-y,m=this.coords[2*h+1]-w,n=this.coords[2*v]-y;v=this.coords[2*v+1]-w;y=this.coords[2*z]-y;z=this.coords[2*z+1]-w;w=n*n+v*v;var L=y*y+z*z;if(0>l*(v*L-w*z)-m*(n*L-w*y)+(l*l+m*m)*(n*z-v*y)){this.triangles[a]=e;this.triangles[d]=h;h=this.halfedges[f];if(-1==h)for(e=this.hullStart;;){if(this.hullTri[e]==f){this.hullTri[e]=a;break}e=this.hullPrev[e];if(e==this.hullStart)break}this.halfedges[a]=h;-1!=h&&(this.halfedges[h]=a);h=this.halfedges[c];
this.halfedges[d]=h;-1!=h&&(this.halfedges[h]=d);this.halfedges[c]=f;-1!=f&&(this.halfedges[f]=c);b<q.EDGE_STACK.length&&(q.EDGE_STACK[b++]=g+(d+1)%3)}else{if(0==b)break;a=q.EDGE_STACK[--b]}}}return c},quicksort:function(a,b){if(20>=b-a)for(var c=a+1,d=b+1;c<d;){var e=c++,g=this.ids[e],f=this.dists[g];for(--e;e>=a&&this.dists[this.ids[e]]>f;)this.ids[e+1]=this.ids[e--];this.ids[e+1]=g}else{g=a+b>>1;c=a+1;d=b;f=this.ids;e=f[g];f[g]=f[c];f[c]=e;this.dists[this.ids[a]]>this.dists[this.ids[b]]&&(g=this.ids,
f=g[a],g[a]=g[b],g[b]=f);this.dists[this.ids[c]]>this.dists[this.ids[b]]&&(g=this.ids,f=g[c],g[c]=g[b],g[b]=f);this.dists[this.ids[a]]>this.dists[this.ids[c]]&&(g=this.ids,f=g[a],g[a]=g[c],g[c]=f);g=this.ids[c];for(f=this.dists[g];;){for(;++c,this.dists[this.ids[c]]<f;);for(;--d,this.dists[this.ids[d]]>f;);if(d<c)break;e=this.ids;var h=e[c];e[c]=e[d];e[d]=h}this.ids[a+1]=this.ids[d];this.ids[d]=g;b-c+1>=d-a?(this.quicksort(c,b),this.quicksort(a,d-1)):(this.quicksort(a,d-1),this.quicksort(c,b))}},
circumradius:function(a,b,c,d,e,g){c-=a;d-=b;a=e-a;var f=g-b;b=c*c+d*d;g=a*a+f*f;e=.5/(c*f-d*a);d=(f*b-d*g)*e;c=(c*g-a*b)*e;return d*d+c*c},circumcenter:function(a,b,c,d,e,g,f){d-=b;e-=c;g-=b;f-=c;var h=d*d+e*e,v=g*g+f*f,q=.5/(d*f-e*g);a.x=b+(f*h-e*v)*q;a.y=c+(d*v-g*h)*q},inCircle:function(a,b,c,d,e,g,f,h){a-=f;b-=h;c-=f;d-=h;e-=f;g-=h;h=c*c+d*d;f=e*e+g*g;return 0>a*(d*f-h*g)-b*(c*f-h*e)+(a*a+b*b)*(c*g-d*e)},pseudoAngle:function(a,b){var c=a/(Math.abs(a)+Math.abs(b));return(0<b?3-c:1+c)/4},hashKey:function(a,
b){var c=a-this.center.x,d=b-this.center.y;c/=Math.abs(c)+Math.abs(d);return Math.floor((0<d?3-c:1+c)/4*this.hashSize)%this.hashSize},link:function(a,b){this.halfedges[a]=b;-1!=b&&(this.halfedges[b]=a)},addTriangle:function(a,b,c,d,e,g){var f=this.trianglesLen;this.triangles[f]=a;this.triangles[f+1]=b;this.triangles[f+2]=c;this.halfedges[f]=d;-1!=d&&(this.halfedges[d]=f);a=f+1;this.halfedges[a]=e;-1!=e&&(this.halfedges[e]=a);e=f+2;this.halfedges[e]=g;-1!=g&&(this.halfedges[g]=e);this.trianglesLen+=
3;return f},orientIfSure:function(a,b,c,d,e,g){d=(d-b)*(e-a);a=(c-a)*(g-b);return Math.abs(d-a)>=3.3306690738754716E-16*Math.abs(d+a)?d-a:0},orient:function(a,b,c,d,e,g){var f=(b-g)*(c-e),h=(a-e)*(d-g);f=Math.abs(f-h)>=3.3306690738754716E-16*Math.abs(f+h)?f-h:0;0==f&&(f=(d-b)*(e-a),h=(c-a)*(g-b),f=Math.abs(f-h)>=3.3306690738754716E-16*Math.abs(f+h)?f-h:0);0!=f?b=f:(a=(g-d)*(a-c),b=(e-c)*(b-d),b=Math.abs(a-b)>=3.3306690738754716E-16*Math.abs(a+b)?a-b:0);return 0>b},swap:function(a,b,c){var d=a[b];
a[b]=a[c];a[c]=d},dist:function(a,b,c,d){a-=c;b-=d;return a*a+b*b}};var ba=function(a,b){this.x=a;this.y=b};q.EPSILON=Math.pow(2,-52);q.EDGE_STACK=new Int32Array(512)})({});var delaunator=$hx_exports.delaunator;